package(default_visibility = ["//visibility:public"])

load("//:defaults.bzl", "ts_library")
load("@build_bazel_rules_nodejs//:index.bzl", "js_library")

js_library(
    name = "nova_wasm_runtime",
    srcs = [
        "pkg/nova_wasm.js",
        "pkg/nova_wasm_bindgen.js",
    ],
)

ts_library(
    name = "nova_wasm",
    module_name = "nova_wasm",
    srcs = [
        "index.ts",
        "pkg/nova_wasm.d.ts",
    ],
    data = [
        ":nova_wasm_runtime",
        "pkg/nova_wasm_bg.wasm",
    ],
)

filegroup(
    name = "artifacts",
    srcs = glob(["pkg/*"]),
)
