/**
 * Writes `src/common/generated_build_version.ts`, the single source of the
 * build stamp that the version handshake compares.
 *
 * WHY A GENERATED SOURCE FILE (and not esbuild's `define`):
 * the server and the client are produced by two different toolchains from
 * one source tree -- `tsc` compiles `server.ts` to `dist/server.js`, and
 * esbuild bundles `src/browser.ts` to `dist/src/browser_bundle.js`. An
 * esbuild `define` only reaches the bundle, so the server would have to
 * learn its version some other way, and the two mechanisms could drift.
 * A generated module is compiled into BOTH outputs from the same text, so
 * the server process and the bundle it serves are identical by
 * construction. This runs first in `npm run build`, before `tsc`.
 *
 * STAMP FORMAT:
 *   clean tree:  <shortSha>
 *   dirty tree:  <shortSha>-dirty-<epochMs>
 *   no git:      nogit-<epochMs>
 *
 * A clean checkout stamps the commit sha alone. A deploy is a commit, so
 * the stamp changes on every deploy; two builds of the same commit produce
 * identical outputs, so it is correct (and cache-friendly) for them to
 * share a stamp -- turbo's build cache still hits. A dirty tree is a dev
 * build whose contents are not identified by the sha, so the wall clock is
 * appended and every rebuild gets a fresh stamp.
 */
import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(
    __dirname, '..', 'src', 'common', 'generated_build_version.ts');

function git(args) {
    return execFileSync('git', args, {
        cwd: __dirname,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
}

function buildVersion() {
    let sha;
    try {
        sha = git(['rev-parse', '--short', 'HEAD']);
    } catch {
        // No git (e.g. a build from a source tarball or a docker context
        // without .git). Fall back to the wall clock, which still changes
        // on every build.
        return `nogit-${Date.now()}`;
    }
    let dirty = true;
    try {
        dirty = git(['status', '--porcelain']).length > 0;
    } catch {
        dirty = true;
    }
    return dirty ? `${sha}-dirty-${Date.now()}` : sha;
}

const version = buildVersion();
const contents = `// GENERATED by scripts/generate_build_version.mjs. Do not edit, do not
// commit (it is gitignored). Regenerated at the start of \`npm run build\`.
export const BUILD_VERSION = ${JSON.stringify(version)};
`;

// Only rewrite when the stamp actually changed, so a no-op rebuild of a
// clean tree does not touch the file's mtime and bust downstream caches.
let existing;
try {
    existing = fs.readFileSync(outPath, 'utf8');
} catch {
    existing = undefined;
}
if (existing !== contents) {
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, contents);
}
console.log(`build version: ${version}`);
