import { Plugin } from "nova_ecs/plugin";
import { DeltaPlugin } from "nova_ecs/plugins/delta_plugin";
import { MovementPlugin } from "nova_ecs/plugins/movement_plugin";
import { TimePlugin } from "nova_ecs/plugins/time_plugin";
import { AnimationPlugin } from "./animation_plugin";
import { BayPlugin } from "./bay_plugin";
import { BeamPlugin } from "./beam_plugin";
import { JettisonPlugin } from "./jettison_plugin";
import { BlastPlugin } from "./blast_plugin";
import { CollisionsPlugin } from './collisions_plugin';
import { ControlsPlugin } from "./controls_plugin";
import { CreateTimePlugin } from "./create_time";
import { DeathPlugin } from "./death_plugin";
import { EntityBudgetPlugin } from "./entity_budget";
import { FireWeaponPlugin } from "./fire_weapon_plugin";
import { HealthPlugin } from "./health_plugin";
import { IonizedPlugin } from "./ionization_plugin";
import { JumpPlugin } from "./jump_plugin";
import { DerelictPlugin } from "./derelict_plugin";
import { NpcInteractionPlugin } from "./npc_interaction_plugin";
import { MissionPlugin } from "./mission_plugin";
import { MissionShipsPlugin } from "./mission_ship_plugin";
import { AsteroidPlugin } from "./asteroid_plugin";
import { LegalRecordPlugin } from "./legal_record_plugin";
import { BoardingPlugin } from "./boarding_plugin";
import { EnergyTransferPlugin } from "./energy_transfer_plugin";
import { AssistancePlugin } from "./assistance_plugin";
import { DisabledPlugin } from "./disabled_plugin";
import { EscortPlugin } from "./escort_plugin";
import { NpcTrafficPlugin } from "./npc_traffic_plugin";
import { PersPlugin } from "./pers_plugin";
import { FleetPlugin } from "./fleet_plugin";
import { PatrolPlugin } from "./patrol_plugin";
import { NpcPlugin } from "./npc_plugin";
import { OutfitPlugin } from "./outfit_plugin";
import { PlanetPlugin } from "./planet_plugin";
import { PlatformPlugin } from "./platform_plugin";
import { ProjectilePlugin } from "./projectile_plugin";
import { PlayerStatePlugin } from "./player_state";
import { ReturnToQueuePlugin } from "./return_to_queue_plugin";
import { ShipController } from "./ship_controller_plugin";
import { ShipPlugin } from "./ship_plugin";
import { TargetPlugin } from "./target_plugin";
import { CloakingPlugin } from "./cloaking_plugin";
import { WeaponPlugin } from "./weapon_plugin";

// Users must add the multiplayer plugin and a display plugin.
// Users must also add the NovaData resource.
export const SystemPlugin: Plugin = {
    name: 'SystemPlugin',
    build(world) {
        world.addPlugin(TimePlugin);
        world.addPlugin(CreateTimePlugin);
        world.addPlugin(EntityBudgetPlugin);
        world.addPlugin(ReturnToQueuePlugin);
        world.addPlugin(PlatformPlugin);
        world.addPlugin(DeltaPlugin);
        world.addPlugin(ShipPlugin);
        world.addPlugin(AnimationPlugin);
        world.addPlugin(ControlsPlugin);
        world.addPlugin(ShipController);
        world.addPlugin(PlanetPlugin);
        world.addPlugin(MovementPlugin);
        world.addPlugin(DeathPlugin);
        world.addPlugin(FireWeaponPlugin);
        world.addPlugin(ProjectilePlugin);
        world.addPlugin(WeaponPlugin);
        world.addPlugin(OutfitPlugin);
        world.addPlugin(PlayerStatePlugin);
        world.addPlugin(CollisionsPlugin);
        world.addPlugin(HealthPlugin);
        world.addPlugin(TargetPlugin);
        world.addPlugin(MissionPlugin);
        world.addPlugin(BeamPlugin);
        world.addPlugin(BayPlugin);
        world.addPlugin(JumpPlugin);
        world.addPlugin(MissionShipsPlugin);
        world.addPlugin(NpcPlugin);
        world.addPlugin(PersPlugin);
    world.addPlugin(FleetPlugin);
    world.addPlugin(PatrolPlugin);
    world.addPlugin(NpcTrafficPlugin);
        world.addPlugin(DisabledPlugin);
        world.addPlugin(BoardingPlugin);
        world.addPlugin(EnergyTransferPlugin);
        world.addPlugin(AssistancePlugin);
        world.addPlugin(EscortPlugin);
        world.addPlugin(AsteroidPlugin);
        world.addPlugin(LegalRecordPlugin);
        world.addPlugin(IonizedPlugin);
        world.addPlugin(BlastPlugin);
        world.addPlugin(JettisonPlugin);
        world.addPlugin(DerelictPlugin);
        world.addPlugin(NpcInteractionPlugin);
        world.addPlugin(CloakingPlugin);
    }
};

