// GENERATED by visual_compare/output/gen_sigma_texts.mjs — do not hand-edit.
//
// The Sigma Shipyards intro mission (mïsn nova:555, "Sigma Shipyards
// Delivery;Sigma1") as the original-hardware captures in
// ui_screenshots/original_macos_screenshots/sigma_mission_1/ show it:
// each dësc's text with the same wildcard values (pilot "Matt" in a
// "Starbridge 525"; 10 tons of equipment from Kolan/Sanddown).
//
//   offer        dësc 4427  (1_sigma_1_offer.png)
//   brief        dësc 5533  (2_sigma_1_accept.png)
//   loadCargo    dësc 7518  (3_sigma_1_pick_up_cargo.png)
//   dropOffCargo dësc 8533  (4_sigma_1_return.png)
//   completion   dësc 9533  (5_sigma_1_mission_text_with_pict.png),
//                           with the dësc Graphic PICT nova:5003
export const SIGMA_TEXTS = {
    offer: "As you wander through the shipyard looking at all the ships awaiting a prospective buyer, a man wearing an expensive tailored business suit comes over and extends his hand.\n\n\"Are you Matt, Captain of the Starbridge 525?\" he asks quietly as you shake hands.  You nod, warily.  \"Excellent, I am Rodney Andrews, manager of shipping liaison for Sigma Shipyards.  Ever since Donald Chick disappeared some months ago we have had a problem gaining the services of freighter pilots to bring in our supplies.  Would you be willing to work for us?\"",
    brief: "\"Great!\" he exclaims with a wide smile.  \"We currently have a shipment of 10 tons of equipment waiting in storage on Kolan in the Sanddown system.  If you could head over there, pick it up and return here, making sure that you land on the area of the Kane Band owned by Sigma Shipyards, that would be great.\n\n\"Any problems?\" he asks seriously.  \"No?  Well, then, I expect that I'll be seeing you again in a few weeks.\"",
    loadCargo: "You quickly find the consignment of 10 tons of equipment that you are after.  The loading staff are very helpful and in under an hour you are ready to begin your return trip.",
    dropOffCargo: "As you pilot your way into what is normally a restricted area, out of bounds to all non-Sigma Shipyards personnel, you take a quick peek at some of the enormous shipyards at their disposal.\n\nAs soon as you land dockworkers swarm all over your vessel and in no time they have unloaded your cargo.  A few minutes later, as you stand around wondering what to do, you spot Rodney coming towards you.\n\n\"Sorry I'm a little tardy,\" he apologizes sincerely, \"I've just been having one of those days today.  Now that I've finally arrived, here are the details I'm sure you're dying to know.\"",
    completion: "\"Firstly,\" Rodney ticks off a finger, \"you have been paid 20000 credits for your services and I have also made available similar missions through the Mission BBS' throughout the Federation.\n\n\"Secondly, as an employee of Sigma Shipyards you are allowed to purchase all the ships in our range,\" he informs you to your delight.  \"In particular I am talking about the Starliner, the Pegasus, and the Leviathan.  If you can scrape together the funds, you can purchase them from here at any time.  You should also be able to find a few ship upgrade outfits available here on the Kane Band.\n\n\"Anyway, if you'll forgive me,\" he finishes a little tiredly, \"I have a thousand and one things I still have to do today, so I'll take my leave of you.  Thanks again.\"",
};

/** The completion dësc's Graphic (the ship on the yellow backdrop). */
export const SIGMA_COMPLETION_PICT = "nova:5003";
